# Generated by Django 2.2.11 on 2022-11-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('introduction', models.CharField(max_length=250, verbose_name='Introduction')),
                ('credit', models.IntegerField(verbose_name='Credits')),
                ('max_number', models.IntegerField(verbose_name='Maximum students allowed')),
                ('year', models.IntegerField(default=2022, verbose_name='Year')),
                ('semester', models.CharField(choices=[('Autumn', 'Fall'), ('Spring', 'Spring')], max_length=20, verbose_name='Semester')),
                ('status', models.IntegerField(verbose_name='Course status')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='Course instructor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('with_draw', models.BooleanField(default=False)),
                ('with_draw_time', models.DateTimeField(default=None, null=True)),
                ('scores', models.IntegerField(null=True, verbose_name='Grades')),
                ('comments', models.CharField(max_length=250, null=True, verbose_name="Instructor's comment")),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='5 being the highest, 1 being the lowest.', null=True, verbose_name="Student's rating")),
                ('assessment', models.CharField(max_length=250, null=True, verbose_name="Student's comment")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Course begin at')),
                ('end_time', models.TimeField(verbose_name='Course end at')),
                ('location', models.CharField(max_length=100, verbose_name='Course location')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('start_week', models.IntegerField(verbose_name='Starting week')),
                ('end_week', models.IntegerField(verbose_name='Ending week')),
                ('week_interval', models.IntegerField(choices=[(1, 'Once every week'), (2, 'Once every two weeks')], default=1, verbose_name='Week intervals')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course name')),
            ],
        ),
    ]
